format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\

$cmd_duration $jobs $time\
$line_break\
$python\
$character"""

[fill]
symbol = " "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

[git_metrics]
disabled = false

[git_commit]
commit_hash_length = 8
style = "bold white"

[python]
python_binary = ['./venv/bin/python', 'python', 'python3']
pyenv_version_name = true

# Components with Dracula Starship Theme
[character]
error_symbol = "[λ](bold #f1fa8c)"
success_symbol = "[λ](bold #f1fa8c)"

[cmd_duration]
style = "bold #f1fa8c"
format = "[$duration]($style)"

[directory]
style = "bold #50fa7b"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[git_branch]
style = "bold #ff79c6"
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
style = "bold #ff5555"
format = '([\[$all_status$ahead_behind\]]($style) )'

[hostname]
style = "bold #bd93f9"
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
disabled = true

[username]
style_user = "bold #8be9fd"
format = "[$user]($style) on "
show_always = false  
